export interface IForecastDay {
    clouds: number,
    dew_point: number,
    dt: number,
    feels_like: any,
    humidity: number,
    pop: number,
    pressure: number,
    snow?: number,
    rain?: number,
    sunrise: number,
    sunset: number,
    temp: any,
    uvi: number,
    weather: any,
    wind_deg: number,
    wind_speed: number,
    wind_gust?: number,
}